FROM node:18-alpine
RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY tsconfig.base.json ./
COPY frontend/package.json frontend/package.json
COPY frontend/package-lock.json frontend/package-lock.json
COPY shared/ ./frontend/shared

WORKDIR /app/frontend
RUN npm install

COPY frontend/ ./

RUN npm run build

CMD ["npm", "run", "start"]
