include:
  - path: backend/docker-compose-prod.yml

services:
  backend:
    image: docker.io/carteado/backend:1.0.0
    container_name: carteado_backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/carteado
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONTEND_URL=http://35.231.34.215
    restart: always
    networks:
      - app_network

  frontend:
    image: docker.io/carteado/frontend:1.0.0
    container_name: carteado_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://35.231.34.215:4000
    restart: always
    networks:
      - app_network
