include:
  - path: backend/docker-compose.yml

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: carteado_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:4000
    networks:
      - carteado_network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: carteado_backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - redis
    networks:
      - carteado_network
    env_file:
      - .env

networks:
  carteado_network:
    name: carteado_network
    driver: bridge
