services:
  nginx:
    image: nginx:latest
    container_name: carteado_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

  frontend:
    image: ferdinandes/carteado-frontend:latest
    container_name: carteado_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://carteado.ferdinandes.com.br
      - NEXTAUTH_URL=http://carteado.ferdinandes.com.br
      - SOCKET_URL=http://carteado.ferdinandes.com.br/socket.io/
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    restart: always
    networks:
      - app_network

  backend:
    image: ferdinandes/carteado-backend:latest
    container_name: carteado_backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - redis
    environment:
      - PORT=4000
      - DATABASE_URL=mongodb://mongodb:27017/carteado?replicaSet=rs0
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://carteado.ferdinandes.com.br
    restart: always
    networks:
      - app_network

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app_network
    command: ["redis-server", "--appendonly", "yes"]

  mongodb1:
    <<: *mongodb_base
    container_name: mongodb1
    ports:
      - "27017:27017"

  mongodb2:
    <<: *mongodb_base
    container_name: mongodb2
    ports:
      - "27018:27017"

  mongodb3:
    <<: *mongodb_base
    container_name: mongodb3
    ports:
      - "27019:27017"

volumes:
  redis_data:
  mongo_data:

networks:
  app_network:
    driver: bridge

x-mongodb_base: &mongodb_base
  image: mongo:6.0
  environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=rootpassword
  volumes:
    - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    - mongo_data:/data/db
  networks:
    - app_network
  command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]