services:
  mongodb:
    build:
      context: ../mongodb_rs
      args:
        MONGO_VERSION: "6.0"
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: carteado
      MONGO_REPLICA_PORT: 27017
      MONGO_REPLICA_HOST: mongodb
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: carteado_redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env

volumes:
  mongo_data:
  redis_data:
