export const testIds = {
  room: {
    stage: "room-stage",
    loading: "room-loading",
    participantsPanel: "room-participants-panel",
    participantsList: "room-participants-list",
    backButton: "room-back-button",
    info: "room-info",
    copyHash: "room-copy-hash",
    chat: "room-chat",
    chatUnread: "room-chat-unread",
    sheet: "room-sheet",
    sheetClose: "room-sheet-close",
    panelToggle: (panel: "chat" | "info") => `room-panel-toggle-${panel}`,
  },
  lobby: {
    ready: "lobby-ready-button",
    startGame: "lobby-start-game-button",
  },
  game: {
    root: "game-root",
    table: "game-table",
    tableLoading: "game-table-loading",
    cardFan: "game-card-fan",
    choosingPhase: "game-choosing-phase",
    confirmHand: "game-confirm-hand",
    pickUpBunch: "game-pick-up-bunch",
    endTurn: "game-end-turn",
    askTruco: "game-ask-truco",
    acceptTruco: "game-accept-truco",
    rejectTruco: "game-reject-truco",
    deckCount: "game-deck-count",
    trucoHud: "game-truco-hud",
    trucoStamp: "game-truco-stamp",
    trickPileOurs: "game-trick-pile-ours",
    trickPileOpponent: "game-trick-pile-opponent",
    currentBet: "game-current-bet",
    xrayPeek: "game-xray-peek",
    radarPeek: "game-radar-peek",
    illusionReveal: "game-illusion-reveal",
    activeEffects: "game-active-effects",
  },
  menu: {
    shell: "menu-shell",
    content: "menu-content",
    friendsPanel: "menu-friends-panel",
    friendsToggle: "menu-friends-toggle",
    friendsList: "menu-friends-list",
    friendRequests: "menu-friend-requests",
    friendSearchResults: "menu-friend-search-results",
  },
} as const;
